DELETE http://localhost:3000/events/611037e61f551536d08c0f21 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMTAzNmI1OWM5OGRkMWQ0NGJhOGVlYSIsImVtYWlsIjoibWF0aWFzQGdtYWlsLmNvbSIsImlhdCI6MTYyODQ1MzA3MSwiZXhwIjoxNjI4NTM5NDcxfQ.Ww4msiuA7cJmBi2amo1XZfT4i92V2JLUuPBtBxV2BL8
